---
general_debian_extra_packages:
  - gpg

general_ufw_ports:
  - port: "22"
    proto: tcp
    state: enabled
    comment: "SSH"

  - port: "8000"
    proto: tcp
    state: enabled
    comment: "Netbox - HTTP"

general_gpg_create_key: true
general_gpg_user: "netbox"
general_gpg_group: "netbox"
