---
general_ufw_ports:
  - port: "{{ general_ssh_port }}"
    proto: tcp
    state: enabled
    comment: "SSH"

  - port: "80"
    proto: tcp
    state: enabled
    comment: "HTTP"

  - port: "111"
    proto: tcp
    state: enabled
    comment: "RPCBIND"
  - port: "111"
    proto: udp
    state: enabled
    comment: "RPCBIND"

  - port: "445"
    proto: tcp
    state: enabled
    comment: "SMB"

  - port: "2049"
    proto: tcp
    state: enabled
    comment: "NFS"
