---
general_ufw_ports:
  - port: "{{ general_ssh_port }}"
    proto: tcp
    state: enabled
    comment: "SSH"

  - port: "5601"
    proto: tcp
    state: enabled
    comment: "KIBANA"

  - port: "8220"
    proto: tcp
    state: enabled
    comment: "FLEET"

  - port: "9200"
    proto: tcp
    state: enabled
    comment: "ELASTICSEARCH"

  - port: "9300"
    proto: tcp
    state: enabled
    comment: "ELASTICSEARCH-CLUSTER"
