---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-secret
  namespace: gitops
spec:
  encryptedData:
    admin.password: AgDOkcGE5gbDrB/CCXAfusC1vE9LAYnQJBxI1eJbGMjQRQkI2jUCrpo/iQ7FMz5r5uVnw97FLD5uFujvx5D2lMw0kp/hAMCynzorcmV7YDnaezqzLXipLErXCVWjf8YNglbfvybPyYMXfaezkkJvLnllKeesV1Sehok2BEQRjNTMTvVjPYPkGHrcW/bE1D6iBzx/NFqo8QWrhbILUF9I5aobkVNrRdhG4cxNU5QeuFtZfPAMLnUZcU4vetnjoLfs+aEF5qoblnOXbGEChgpzHhtEZdnpttGrfsE0qetIqodfN2JbsE50RU0rHTlE3iS5mKw6yg4sH4GRGHSJcs+eOMtyFNYFPDVnrnREXSrnQNwNqo0OY2SLjgZonBhtOsnS/Cugn9ioRloBEzLHnhylwwu9Xr93Qq24sCKLsLQ5bJGK6yeZJUtGBdZjsksOxpYr5omotagBP2VbGuIJfBnGSgc1G1X+6qLYu0XTXAC28ELRxJTirrEQbwiovR7Vh0Fx7o69Yk2ludu+JMb3bxBy/uC3LkkEQOhIDK1rE/kdpcYRcWd9K5Lj9oiuYmMJd/sPIztSnQwiN1Jsq6kypIFkdd+MyMxMb+/mDor1cxWJrNRQ1+m+JkQomqANP+GWEO+8ThIeRVTjAUmonSebLcEfBNk9qc96wNKNm7+kNfAcEpFB7A0rdkUpQK04bfIR7wWRd3lbh+PEPYGqYR8/SFiVT2C4aG8gpa7Ug1ZL6PolEWI3+K9oHHRBkgMaE18k6DTjOvjdhvm3eBbL+RQhsCM=
    admin.passwordMtime: AgBaGkWcyPa9HNcyD3Afbmk0DMyk7ZFaqzvh/7+vLv74y+u1u8oCJnQY3kHNDhLiyeRWXyWgeiyUNtz/DJyINPIQJKvPpqxPbNZuv2x1IIjXdSdbsHW4QuEefXhmzOpRPoNV+yiPTYVOJHM2QCDvE/BILioLTF8BbQnLw/YLwHpyBTcLonmhke4vxYZyZXyoj5cBvgq9rX8IgQ1pt1yx2w4a+BqTe1B5QpyX11v1SRZWIXXb3BuM0Y7/30qLbTBuvbevGNJ4fFMDhK0pFAoWoS0aKwn5PHNDAwZ8XALecEwROq5ho1Vj53AIX9xpSpIOFYAJ+Vl7esSI3pK2mkGS9RZMjQ3ZLqRhzZpsEKC/8JQC2YiWCpH9yD+SJrjTEJZPcfpu/ftqmsFaUaIOulRvkkkUbAoxlHPPJXHjor8CV4+Ax2GaFbMTBFbozTDSo+YTUpjxXuJKAsSR6y/leKILBLUwYW10+/FTf99e+WOKf4sLWFxxf+LykCBAd2RrIsd8bWagvZZRG6mdmsvxXTtxOCKqfayBCz5a6X7jrHcLBB6bQeqUhCUSM6tqW09h0CZ0/kNuh2FppXhDvdTpJ/EI2tk6cx2fNUZwB8oxWPJ775HmjmfDPkFWd3N0KuNlF55t8Hr/bQd3WZzjgk9Q/irLsF/uTw4wWnKF+uBaN04I8I0BSrLiI43Dn2Jx0LfD89CqSehWDszH33xrtCKx74B3USPcqHelBUsi
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: gitops
    type: Opaque
