---
bind9_masters:
  - { name: dns-01.core.internal, addresses: [10.1.100.11] }
bind9_forward: true
bind9_forward_servers:
  - 1.1.1.1

bind9_zones_dynamic:
  - name: redstone
    type: slave
    masters:
      - 10.1.100.11
  - name: bluecore
    type: slave
    masters:
      - 10.1.100.11
  - name: core.internal
    type: slave
    masters:
      - 10.1.100.11
  - name: identity.internal
    type: slave
    masters:
      - 10.1.100.11
  - name: secrets.internal
    type: slave
    masters:
      - 10.1.100.11
  - name: redstone.internal
    type: slave
    masters:
      - 10.1.100.11

bind9_recursor: true
bind9_our_networks:
  - localhost
  - localnets
  - 192.168.178.0/24
  - 10.1.100.0/24
  - 10.1.110.0/24
  - 10.1.115.0/24
  - 10.2.100.0/24
