apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/cloudnativepg
patches:    
  - target:
      kind: HelmRelease
      name: cnpg
    patch: |
      - op: add
        path: /spec/values/config/data
        value: 
          WATCH_NAMESPACE: scraper
