kubernetes:
  children:
    k8s-dev-01-master:
    k8s-dev-01-node:

k8s-dev-01-master:
  hosts:
    k8s-dev-01-master-01:
      ansible_host: k8s-dev-01-master-01

k8s-dev-01-node:
  hosts:
    k8s-dev-01-node-01:
      ansible_host: k8s-dev-01-node-01
    k8s-dev-01-node-02:
      ansible_host: k8s-dev-01-node-02
    k8s-dev-01-node-03:
      ansible_host: k8s-dev-01-node-03

dev-01-nfs:
  hosts:
    dev-01-nfs-01:
      ansible_host: dev-01-nfs-01
