---
prometheus_scrape_configs:
  - job_name: vault
    metrics_path: /v1/sys/metrics
    params:
      format: ['prometheus']
    scheme: https
    authorization:
      credentials_file: /etc/prometheus/vault-token
    static_configs:
      - targets: ['vault.secrets.internal:8200']
  - job_name: node
    static_configs:
      - targets:
          - 'dns-01.core.internal:9100'
          - 'dns-02.core.internal:9100'
          - 'netbox-01.core.internal:9100'
          - 'backup-01.core.internal:9100'
          - 'backup-02.core.internal:9100'
          - 'gh-runner-01.core.internal:9100'
          - 'loadbalancer-01.core.internal:9100'
          - 'loadbalancer-02.core.internal:9100'
          - 'monitoring-01.core.internal:9100'
          - 'vault-01.secrets.internal:9100'
          - 'vault-02.secrets.internal:9100'
          - 'vault-03.secrets.internal:9100'
          - 'keycloak-01.identity.internal:9100'
