apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- ../../base/kube-prometheus-stack/
- podmonitor.yaml
configMapGenerator:
  - name: flux-kube-state-metrics-config
    files:
      - kube-state-metrics-config.yaml
    options:
      labels:
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
configurations:
  - kustomizeconfig.yaml
patches:
  - target:
      kind: HelmRelease
      name: kube-prometheus-stack
      version: v2
      group: helm.toolkit.fluxcd.io
    patch: |-
      - op: add
        path: /spec/valuesFrom
        value: []
  - target:
      kind: HelmRelease
      name: kube-prometheus-stack
      version: v2
      group: helm.toolkit.fluxcd.io
    patch: |-
      - op: add
        path: /spec/valuesFrom/0
        value:
          kind: ConfigMap
          name: flux-kube-state-metrics-config
          valuesKey: kube-state-metrics-config.yaml





# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: kube-prometheus-stack
#   namespace: monitoring
# spec:
#   interval: 30m
#   chart:
#     spec:
#       chart: kube-prometheus-stack
#       version: "69.x"
#       sourceRef:
#         kind: HelmRepository
#         name: kube-prometheus-stack
#         namespace: monitoring
#       interval: 12h
#   valuesFrom:
#   - kind: ConfigMap
#     name: flux-kube-state-metrics-config
#     valuesKey: kube-state-metrics-config.yaml
