---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: airflow
  namespace: airflow
spec:
  interval: 30m
  chart:
    spec:
      chart: airflow
      version: "8.9.0"
      sourceRef:
        kind: HelmRepository
        name: airflow
        namespace: airflow
      interval: 1m
