---
alloy_user_groups:
  - systemd-journal

alloy_config: |
  loki.write "default" {
    endpoint {
      url = "http://monitoring-01.core.internal:3100/loki/api/v1/push"
    }
  }

  loki.source.journal "systemd" {
    forward_to = [
      loki.write.default.receiver,
    ]
    labels = {
      host = constants.hostname,
      env  = "dev",
    }
  }

  loki.source.file "vault_backup" {
    targets = [
      {
        __path__ = "/var/log/vault-backup.log",
        service = "vault-backup",
        host = constants.hostname,
      },
    ]

    forward_to = [
      loki.write.default.receiver,
    ]
  }
