vault_address: "0.0.0.0"
server_url: vault.secrets.internal
vault_api_addr: "https://{{ server_url }}"
vault_tls_disable: 'false'
vault_tls_copy_keys: "false"
vault_tls_private_path: "/etc/vault/tls"
vault_tls_certs_path: /etc/vault/tls
vault_tls_key_file: "server.key"
vault_tls_cert_file: "fullchain.pem"
vault_dotfile_disable: true
vault_telemetry_enabled: true

vaults:
  vault:
    address: vault.secrets.internal
  vault_01:
    address: vault-01.secrets.internal
    ip: 10.1.115.11
  vault_02:
    address: vault-02.secrets.internal
    ip: 10.1.115.12
  vault_03:
    address: vault-03.secrets.internal
    ip: 10.1.115.13
