---
nfs_exports:
  - "/mnt/data/grafana    *(rw,sync,no_subtree_check,no_root_squash)"
  - "/mnt/data/pgdata    *(rw,sync,no_subtree_check,no_root_squash)"
  - "/mnt/data/pgdata2    *(rw,sync,no_subtree_check,no_root_squash)"
  - "/mnt/data/pgdata3    *(rw,sync,no_subtree_check,no_root_squash)"
  - "/mnt/data/pgadmin    *(rw,sync,no_subtree_check,no_root_squash)"
