---
# ssl configs
haproxy_stats_address: "0.0.0.0"
haproxy_stats_port: 8500

haproxy_resolvers:
  - name: "core"
    servers:
      - name: "dns-01.core.internal"
        address: "dns-01.core.internal:53"
      - name: "dns-02.core.internal"
        address: "dns-02.core.internal:53"

haproxy_frontends:
  - name: "https"
    address: "0.0.0.0"
    port: 443
    ssl_enable: true
    ssl_certificates:
      - "/etc/haproxy/certs/keycloak.pem"
      - "/etc/haproxy/certs/vault.pem"
    routes:
      - acl_name: "is_vault"
        acl_condition: "hdr(host) -i vault.secrets.internal"
        backend_name: "vault_backend"

      - acl_name: "is_keycloak"
        acl_condition: "hdr(host) -i keycloak.identity.internal"
        backend_name: "keycloak_backend"
    options:
      - "httplog"

  - name: "vault"
    address: "0.0.0.0"
    port: 8200
    mode: "tcp"
    default_backend: "vault_backend_tcp"

haproxy_backends:
  - name: "vault_backend"
    mode: "http"
    balance: "first"
    port: 8200
    ssl_enable: true
    verify: "none"
    check: true
    options:
      - httpchk
    http_check:
      send:
        method: GET
        uri: /v1/sys/health
      expect: status 200
    servers:
      - name: vault-01.secrets.internal
        address: vault-01.secrets.internal
        resolver: "core"
        init_addr: "none"
      - name: vault-02.secrets.internal
        address: vault-02.secrets.internal
        resolver: "core"
        init_addr: "none"
      - name: vault-03.secrets.internal
        address: vault-03.secrets.internal
        resolver: "core"
        init_addr: "none"
  - name: "vault_backend_tcp"
    mode: "tcp"
    balance: "first"
    port: 8200
    check: true
    http_check:
      send:
        method: GET
        uri: /v1/sys/health
      expect: status 200
    options:
      - ssl-hello-chk
    servers:
      - name: vault-01.secrets.internal
        address: vault-01.secrets.internal
        resolver: "core"
        init_addr: "none"
      - name: vault-02.secrets.internal
        address: vault-02.secrets.internal
        resolver: "core"
        init_addr: "none"
      - name: vault-03.secrets.internal
        address: vault-03.secrets.internal
        resolver: "core"
        init_addr: "none"

  - name: "keycloak_backend"
    mode: "http"
    balance: "first"
    port: 8080
    check: true
    check_port: 8080
    headers:
      X-Forwarded-Proto: https
      X-Forwarded-Port: 443
      X-Forwarded-Host: "keycloak.identity.internal"
    servers:
      - name: keycloak-01.identity.internal
        address: keycloak-01.identity.internal
        resolver: "core"
        init_addr: "none"
