---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: "8.9.1"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
      interval: 12h
  values:
    admin:
    sidecar:
      datasources:
        enabled: true
        label: grafana_datasource
        labelValue: "1"
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        searchNamespace: ALL
        provider:
          allowUiUpdates: true

    persistence:
      enabled: true
      type: pvc
      accessModes:
        - ReadWriteOnce
      size: 10Gi
      extraPvcLabels:
        type: grafana-pvc
