---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAUWHQWnc5BGIzVqi4RrHY03IGpmBDmHFYJuNlqKcnbeTXqCDSG+R8RNVmkCN7sm/wGdZWps4T64TvwXVQzII/1EI2INs8fh4GnQa8+cx0o+eAwlQLY8xuaxirS7e9cwE07+D9Lz7o6tgOR3RqHFgeGIFQbVQL3TUq+e+KeMAt3PoNYh7YRzXdQOxFtRuuak6q19YxyQDSxd4oLBTAUSPjaiHvPsn7QHdS+5OUGzON+vf2jFJME4C5Q+MXl9yXLYWDOqO4ZkVKS7lmwkEcSqlRevEIp0u8NKiyj1W0cw6AzYpdnYBNEct09Vo6uJcSrvBTXkn6dR9tB7LFcBS8mstIj3L5+VHAl1+Yig03Cr9GJNr4cYQvTc/sSc93gDxpqZBHNxQhh9mlX9A+Bs6ANJ/Oq3+8VzbboiIPGqG4ruRlvYtdE8VscRK6CUwT3X6JEa0tJ5byD1P+FxK6ct2OPqgIOD5VVGiqhr8EkGPR5GdOrrmRVQmWJaCU4xAMHuDliZp1HOEky/hPJo6P+yMVM0O+B1JhhDZTguT3gr/nidND8mUvO49vqA/EU0zZwwNmsstHZKC2vuKgJTUaw22oe447NbvKH85PYco8NeQCiSVWpmsIaI2P2VeyYYAxyhhZrwdvz5XCUTP1pZluJwWqtRAbNpklAMj7k2/FtpsdzcQqbhoOl5YhP5ymmTMeay4yeI6MEJrIIbF0XE9Y9IA==
    admin-user: AgBBvpqDSaOG8JYa0s/u1ceTvm+xM579AWXKiz+XhEtkLMQa7c8wcb3ZPAt0IMHsyJdyKwKNCrfKZeBWcDJ6iw77+2nld4ypY0x33oCCO0qxu/ar3QsQnTiMK1J5XDWVY1JCAw1SVGtAe0rg4K4H0hrrY2oLUic+U/ZXsMys3rkwg3NEHa4R5Z6lbsmbLQR6vQY+5ES7X36T/lor+f8QD7uhtOPso5J7tr/B8JgBLZ45d7JextI4yqoUAAe1g7NVd94Wd8LPKDTwVsDMSlF/gBbZ3XehGnBCzQYxAb4Re6ZkunQe08EyYeVkWtPNkQxp84atLCVRUVKrGdyBHp6PZGrv3EXA33zzVU9q+XJ8Pa2RXBae94T8Z0ZIXhUFpOWdJmUaoS1l10XOZAY9QSc3SS0Bp+3SAveSg19PTagjpfHT7xoHo8F85sQJ+kAe5tMvbcat7/T6WdjTu03muiVXAIaXSMORJZ77P0LF7SRywe4Fu2PUMdpQVPcDHOYIpxvy4bf/d9uy6R92zWs6KfEZFZAdDf1p9oKoML7m9G3LDwI7RK4Gz2BZEEeSb2DUlLXQlA0OjamwYlLVm0LzPB4brPDsgLBKJZhdYxIEVy4EeqJY2/JJQZjijeG8o6XGZO9PbN75pOEmdWOmmHDfre/xNfUllVC2Z/bG7XhawQ2Jn76WUXDnUAhGK3K8ffBIVWlT2p8l4JLO
  template:
    metadata:
      annotations:
        sealedsecrets.bitname.com/managed: "true"
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring
