apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - patch: |-
      - op: add
        path: "/spec/values/admin/existingSecret"
        value: "grafana-secret"
    target:
      kind: HelmRelease
      name: grafana
resources:
- ../../base/grafana/datasource.yaml
- ../../base/grafana/release.yaml
- ../../base/grafana/repository.yaml
- pv.yaml
- grafana-secret.yaml
