---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: monitoring
spec:
  interval: 1h
  values:
    containerPort: 4443
    args:
      - --secure-port=4443
      - --kubelet-insecure-tls
  chart:
    spec:
      chart: metrics-server
      version: "3.12.2"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: monitoring
      interval: 1h
