- name: Install docker registry
  hosts: registry
  gather_facts: true
  roles:
    - role: geerlingguy.docker
    - role: tinslice.ansible-role-disks
  post_tasks:
    - name: Get docker-compose file
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        mode: 755
      loop: "{{ docker_file_urls }}"
    - name: Start docker
      ansible.builtin.command:
        cmd: "docker-compose -f {{ item.dest }} up -d"
      changed_when: false
      loop: "{{ docker_file_urls }}"
