- name: Install acme
  hosts: loadbalancer
  gather_facts: true
  roles:
    - role: reneruprecht.acme
    - role: geerlingguy.nginx

- name: Install vault
  hosts: vault
  gather_facts: true
  roles:
    - role: ansible-community.ansible-vault
  post_tasks:
    - name: Set vault environment
      ansible.builtin.lineinfile:
        path: "~/.bashrc"
        line: "export VAULT_ADDR={{ vault_api_addr }}"
        state: present

- name: Install nfs
  hosts: nfs
  gather_facts: true
  roles:
    - role: geerlingguy.nfs
    - role: tinslice.ansible-role-disks

- name: Install nfs
  hosts: k8s-01
  gather_facts: true
  tasks:
    - name: Install nfs common
      ansible.builtin.apt:
        name: "nfs-common"
        update_cache: true

- name: Install k8s
  hosts: k8s-01
  gather_facts: true
  roles:
    - role: reneruprecht.kubernetes

- name: Install docker registry
  hosts: registry
  gather_facts: true
  roles:
    - role: geerlingguy.docker
    - role: tinslice.ansible-role-disks
  post_tasks:
    - name: Get docker-compose file
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
        mode: 755
      loop: "{{ docker_file_urls }}"
    - name: Start docker
      ansible.builtin.command:
        cmd: "docker-compose -f {{ item.dest }} up -d"
      changed_when: false
      loop: "{{ docker_file_urls }}"
