patterns:
  dns.yml:
    - "dns-*"
    - "dns" 
  consul.yml:
    - "consul-*"
    - "consul" 
  loadbalancer.yml:
    - "loadbalancer-*"
    - "loadbalancer" 
  netbox.yml:
    - "netbox-*"
    - "netbox" 
  gh-runner.yml:
    - "gh-runner-*"
    - "gh-runner" 
    - "gh_runner" 
  vault.yml:
    - "vault-*"
    - "vault" 
  k8s.yml:
    - "k8s_01_*"
    - "k8s-master-*"
    - "k8s-node-*"
    - "k8s-node-*"
  k8s-vault.yml:
    - "k8s_vault_*"
    - "k8s-vault-*"
  monitoring.yml:
    - "monitoring-*"
    - "monitoring" 
  keycloak.yml:
    - "keycloak-*"
    - "keycloak" 
  backup.yml:
    - "backup-*"
    - "backup" 
