---
collections:
  - name: ansible.posix
    version: "2.0.0" 
roles:
  - name: reneruprecht.kubernetes
    src: "https://github.com/reneruprecht/ansible-role-kubernetes"
    scm: git
    version: main
  - name: geerlingguy.nfs
    version: "2.1.0"
