apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 10Gi
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: grafana
    namespace: monitoring
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/data/grafana
    server: nfs-01.redstone
