---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: gitops
spec:
  secretName: argocd-cert-tls
  commonName: argocd.redstone
  dnsNames:
    - argocd.redstone
  issuerRef:
    name: pki-int-redstone
    kind: ClusterIssuer
  privateKey:
    algorithm: RSA
    size: 4096
