---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-cert
  namespace: harbor
spec:
  secretName: harbor-cert-tls
  commonName: harbor.redstone
  dnsNames:
    - harbor.redstone
    - core.harbor.redstone
  issuerRef:
    name: pki-int-redstone
    kind: ClusterIssuer
  privateKey:
    algorithm: RSA
    size: 4096
