---
- name: Install keycloak
  hosts: keycloak
  gather_facts: true
  roles:
    - role: reneruprecht.general
    - role: geerlingguy.docker
    - role: prometheus.prometheus.node_exporter
    - role: reneruprecht.keycloak
  vars:
    keycloak_auth_username: "admin"
    keycloak_auth_password: "admin"

    keycloak_groups:
      - name: homelab-admins
        realm: homelab
      - name: homelab-users
        realm: homelab
      - name: homelab-operators
        realm: homelab

    keycloak_roles:
      - name: admins
        realm: homelab
        state: absent
      - name: users
        realm: homelab
        state: absent
      - name: operators
        realm: homelab
        state: absent

  tasks:
    - name: Create Keycloak realm
      delegate_to: localhost
      community.general.keycloak_realm:
        auth_client_id: admin-cli
        auth_keycloak_url: https://keycloak.identity.internal
        auth_realm: master
        auth_username: "{{ keycloak_auth_username }}"
        auth_password: "{{ keycloak_auth_password }}"
        realm: homelab
        enabled: true
        display_name: homelab
        state: present

    - name: Create a Keycloak group, authentication with credentials
      delegate_to: localhost
      community.general.keycloak_group:
        name: "{{ item.name }}"
        realm: "{{ item.realm }}"
        state: "{{ item.state | default('present') }}"
        auth_client_id: admin-cli
        auth_keycloak_url: https://keycloak.identity.internal
        auth_realm: master
        auth_username: "{{ keycloak_auth_username }}"
        auth_password: "{{ keycloak_auth_password }}"
      loop: "{{ keycloak_groups }}"

    - name: Create a Keycloak realm role
      delegate_to: localhost
      community.general.keycloak_role:
        name: "{{ item.name }}"
        realm: "{{ item.realm }}"
        state: "{{ item.state | default('present') }}"
        auth_client_id: admin-cli
        auth_keycloak_url: https://keycloak.identity.internal
        auth_realm: master
        auth_username: "{{ keycloak_auth_username }}"
        auth_password: "{{ keycloak_auth_password }}"
      loop: "{{ keycloak_roles }}"

    - name: Create user
      community.general.keycloak_user:
        auth_keycloak_url: https://keycloak.identity.internal
        auth_username: "{{ keycloak_auth_username }}"
        auth_password: "{{ keycloak_auth_password }}"
        auth_realm: master
        realm: homelab
        username: homelab
        firstName: homelab
        lastName: admin
        email: homelab@homelab.internal
        enabled: true
        emailVerified: true
        credentials:
          - type: password
            value: password
            temporary: false
        groups:
          - name: homelab-admins
            state: present
        state: present

    - name: Create Keycloak client_scope
      community.general.keycloak_clientscope:
        auth_keycloak_url: https://keycloak.identity.internal
        auth_username: "{{ keycloak_auth_username }}"
        auth_password: "{{ keycloak_auth_password }}"
        auth_realm: master

        realm: homelab

        name: groups
        description: "User group membership for OIDC clients"

        protocol: openid-connect

        state: present

        protocol_mappers:
          - name: groups
            protocol: openid-connect
            protocolMapper: oidc-group-membership-mapper
            config:
              full.path: "false"
              id.token.claim: "true"
              access.token.claim: "true"
              userinfo.token.claim: "true"
              claim.name: "groups"

      delegate_to: localhost

    - name: Create Keycloak client
      community.general.keycloak_client:
        auth_keycloak_url: https://keycloak.identity.internal
        auth_username: "{{ keycloak_auth_username }}"
        auth_password: "{{ keycloak_auth_password }}"
        auth_realm: master

        state: present

        realm: homelab

        client_id: grafana
        name: Grafana

        enabled: true

        protocol: openid-connect
        protocol_mappers:
          - name: groups
            protocol: openid-connect
            protocolMapper: oidc-group-membership-mapper
            config:
              full.path: "false"
              id.token.claim: "true"
              access.token.claim: "true"
              userinfo.token.claim: "true"
              claim.name: "groups"

        standard_flow_enabled: true
        direct_access_grants_enabled: true
        service_accounts_enabled: false

        public_client: false
        client_authenticator_type: client-secret
        secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          36323734633533396231306536373435643938363634633061303038393662343435376533666565
          6164623534323963353363616132393362613832393065610a643336666339613332353362393730
          64663961616265326439313130316534306638326463393036623865383737656532366361393234
          6638343763376236340a303633653537346664616466633431663164343731633963353265343733
          6232


        client_scopes_behavior: idempotent
        default_client_scopes:
          - email
          - offline_access
          - roles
          - profile
          - groups

        root_url: https://grafana.core.internal

        redirect_uris:
          - https://grafana.core.internal/login/generic_oauth

        web_origins:
          - https://grafana.core.internal

        full_scope_allowed: false
      delegate_to: localhost
