apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: scraper-db
  namespace: scraper
spec:
  instances: 3
  superuserSecret:
    name: postgres
  bootstrap:
    initdb:
      database: dbx
      owner: postgresuser
      secret:
        name: postgres
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
