apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-my-db-pv
  namespace: scraper
spec:
  capacity:
    storage: 10Gi
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: scraper-db-1
    namespace: scraper
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/data/pgdata
    server: nfs-01.redstone
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-my-db-pv2
  namespace: scraper
spec:
  capacity:
    storage: 10Gi
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: scraper-db-2
    namespace: scraper
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/data/pgdata2
    server: nfs-01.redstone
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-my-db-pv3
  namespace: scraper
spec:
  capacity:
    storage: 10Gi
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: scraper-db-3
    namespace: scraper
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /mnt/data/pgdata2
    server: nfs-01.redstone
