---
- name: Prepare Elastic
  hosts: elastic
  gather_facts: true
  roles:
    - role: reneruprecht.general

- name: Install Elastic
  hosts: elastic
  gather_facts: true
  vars:
    elasticsearch_service_state: "stopped"
  roles:
    - role: reneruprecht.elasticsearch
  post_tasks:
    - name: Ensure vault-agent group exists
      become: true
      ansible.builtin.group:
        name: "{{ vault_agent_group }}"
        state: present

    - name: Include elastic-vault-agent
      ansible.builtin.include_tasks:
        file: ./tasks/vault-agent-elastic.yml

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Wait for trigger directory
      become: true
      ansible.builtin.wait_for:
        path: "{{ elasticsearch_security_http_ssl_key }}"
        state: present
        timeout: 20

    - name: Start elasticsearch
      become: true
      ansible.builtin.systemd:
        name: elasticsearch
        state: started

  handlers:
    - name: Restart vault-agent
      become: true
      ansible.builtin.systemd:
        name: vault-agent
        state: restarted
        daemon_reload: true

- name: Bootstrap Elastic
  hosts: elastic
  gather_facts: true
  tags:
    - never
    - bootstrap
  roles:
    - role: reneruprecht.elasticsearch

- name: Install Kibana
  hosts: elastic
  gather_facts: true
  roles:
    - role: reneruprecht.kibana
