---
- name: Prepare Elastic
  hosts: elastic
  gather_facts: true
  roles:
    - role: reneruprecht.general

- name: Install Elastic
  hosts: elastic
  gather_facts: true
  vars:
    elasticsearch_service_state: "stopped"
  roles:
    - role: reneruprecht.elasticsearch
  post_tasks:
    - name: Include elastic-vault-agent
      ansible.builtin.include_tasks:
        file: ./tasks/vault-agent-install.yml

    - name: Start elasticsearch
      become: true
      ansible.builtin.systemd:
        name: elasticsearch
        state: started


- name: Bootstrap Elastic
  hosts: elastic
  gather_facts: true
  tags:
    - never
    - bootstrap
  roles:
    - role: reneruprecht.elasticsearch

- name: Install Kibana
  hosts: elastic
  gather_facts: true
  roles:
    - role: reneruprecht.kibana

- name: Install fleet server
  hosts: elastic
  gather_facts: true
  roles:
    - role: reneruprecht.elastic-agent
