---
- name: Install general loadbalancer
  hosts: loadbalancer
  become: true
  gather_facts: true
  roles:
    - role: reneruprecht.general

- name: Install loadbalancer
  hosts: loadbalancer
  gather_facts: true
  roles:
    - role: reneruprecht.haproxy
    - role: evrardjp.keepalived
      become: true
    - role: prometheus.prometheus.node_exporter
    - role: prometheus.prometheus.blackbox_exporter
  post_tasks:
    - name: Include haproxy_vault_agent
      ansible.builtin.include_tasks:
        file: ./tasks/vault-agent-install.yml

- name: Install loadbalancer
  hosts: loadbalancer
  gather_facts: true
  roles:
    - role: reneruprecht.elastic-agent
