---
- name: Install monitoring vms
  hosts: monitoring
  gather_facts: true
  roles:
    - role: reneruprecht.general
    - role: grafana.grafana.loki
      become: true
    - role: prometheus.prometheus.prometheus
    - role: prometheus.prometheus.node_exporter
    - role: grafana.grafana.grafana
  post_tasks:
    - name: Include prometheus vault agent
      ansible.builtin.include_tasks:
        file: ./tasks/vault-agent-prometheus.yml
  handlers:
    - name: Restart vault-agent
      become: true
      ansible.builtin.systemd:
        name: vault-agent
        state: restarted
        daemon_reload: true
