- name: Setup Opnsense
  hosts: firewalls
  connection: local
  gather_facts: false
  module_defaults:
    group/oxlorg.opnsense.all:
      firewall: 'opnsense-01.core.internal'
      api_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33376666376264306166366333346532383965653366623330376365383932313265383637313737
          3862396637373938663835626561303235376235363330360a643262386132626563306262313635
          36616266626633326265383064316662366532633563363230373361363061376632353137353339
          3034353864616335630a323961633634323665656334356431323562653333383034303537343037
          35333564336131386334646337333665366234366137393435643332626339663861646332646561
          35666438636331316334373831333365396562653063326436323961653661323965616533306634
          62313932333065616535373261333939623030643938623535653539623439653863626362646531
          63343630623032306461326566316666376261653031633162356239313265313331646165613835
          6534
      api_secret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37363333313262643231653262333164393366663533383732356463623562653933396363636163
          3636643932633466636133633436653039323561386631630a343435303333613561653365306133
          30393664303837313331653565323331353833343062386435303033313639643766656163646362
          3138623533653235650a663538656237373333613435646332333334383236633136313064363037
          35373736323466353165393762303866636264363533656233363136666561336537303532346336
          37623264326662363862343534303734643035383731326134653239326563393065346662356635
          39343735643931343132623134626663393939376565383836313836386638313561373236643061
          36653433613432643830633736303865373463643839656332633666376266336361333138366565
          3461
      ssl_verify: false

    oxlorg.opnsense.list:
      target: 'interface_vlan'

    oxlorg.opnsense.rule:
      match_fields: ['description']
  vars:
    vlans:
      - vlan: 100
        interface: "vtnet1"
        description: "Core"
      - vlan: 110
        interface: "vtnet1"
        description: "Identity"
      - vlan: 115
        interface: "vtnet1"
        description: "Secrets"
      - vlan: 200
        interface: "vtnet1"
        description: "Redstone"

    mgmt_rules:
      allow_mgmt_to_opnsense_https:
        action: 'pass'
        int: ['wan']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP'
        src: '192.168.178.0/24'
        dest: '192.168.178.80'
        dest_port: 'https'
        quick: true
        log: false
        seq: 100
        state: 'present'

      allow_mgmt_to_core_lb_https:
        action: 'pass'
        int: ['wan']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP'
        src: '192.168.178.0/24'
        dest: 'CORE_LBS'
        dest_port: 'https'
        quick: true
        log: false
        seq: 100
        state: 'present'

      allow_mgmt_to_core_lb_stats:
        action: 'pass'
        int: ['wan']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP'
        src: '192.168.178.0/24'
        dest: 'CORE_LBS'
        dest_port: '8500'
        quick: true
        log: false
        seq: 100
        state: 'present'

      allow_mgmt_to_core_ssh:
        action: 'pass'
        int: ['wan']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP'
        src: '192.168.178.0/24'
        dest: '10.1.100.0/24'
        dest_port: 'ssh'
        quick: true
        log: false
        state: 'present'

      allow_mgmt_to_core_icmp:
        action: 'pass'
        int: ['wan']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'icmp'
        src: '192.168.178.0/24'
        dest: '10.0.0.0/8'
        quick: true
        log: false
        state: 'present'

      allow_mgmt_to_core_dns:
        action: 'pass'
        int: ['wan']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP/UDP'
        src: '192.168.178.0/24'
        dest: 'CORE_DNS'
        dest_port: '53'
        quick: true
        log: false
        state: 'present'

      allow_mgmt_to_minio_http:
        action: 'pass'
        int: ['wan']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP'
        src: '192.168.178.0/24'
        dest: 'CORE_BACKUP'
        dest_port: '9001'
        quick: true
        log: false
        state: 'present'

      allow_mgmt_to_minio_api:
        action: 'pass'
        int: ['wan']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP'
        src: '192.168.178.0/24'
        dest: 'CORE_BACKUP'
        dest_port: '9000'
        quick: true
        log: false
        state: 'present'

      allow_mgmt_to_netbox_http:
        action: 'pass'
        int: ['wan']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP'
        src: '192.168.178.0/24'
        dest: '10.1.100.13'
        dest_port: '8000'
        quick: true
        log: false
        state: 'present'

      allow_mgmt_to_redstone_ssh:
        action: 'pass'
        int: ['wan']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP'
        src: '192.168.178.0/24'
        dest: '10.2.100.0/24'
        dest_port: 'ssh'
        quick: true
        log: false
        state: 'present'

      allow_mgmt_to_redstone_kubernetes:
        action: 'pass'
        int: ['wan']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP'
        src: '192.168.178.0/24'
        dest: '10.2.100.12/24'
        dest_port: '6443'
        quick: true
        log: false
        state: 'present'

      allow_mgmt_to_identity_ssh:
        action: 'pass'
        int: ['wan']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP'
        src: '192.168.178.0/24'
        dest: '10.1.110.0/24'
        dest_port: 'ssh'
        quick: true
        log: false
        state: 'present'

      allow_mgmt_to_secrets_ssh:
        action: 'pass'
        int: ['wan']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP'
        src: '192.168.178.0/24'
        dest: '10.1.115.0/24'
        dest_port: 'ssh'
        quick: true
        log: false
        state: 'present'

      allow_mgmt_to_vault_ui:
        action: 'pass'
        int: ['wan']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP'
        src: '192.168.178.0/24'
        dest: 'CORE_LBS'
        dest_port: '8200'
        quick: true
        log: false
        state: 'present'

      allow_mgmt_to_keycloak:
        action: 'pass'
        int: ['wan']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP'
        src: '192.168.178.0/24'
        dest: 'IDENTITY_KEYCLOAK'
        dest_port: '8080'
        quick: true
        log: false
        state: 'present'

    core_rules:
      allow_vlan_core_out:
        action: 'pass'
        int: ['opt1']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'any'
        src: '10.1.100.0/24'
        dest: 'any'
        quick: true
        log: false
        state: 'present'

      allow_core_lb_to_vault_api:
        action: 'pass'
        int: ['opt1']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP'
        src: 'CORE_LBS'
        dest: 'SECRETS_VAULT'
        dest_port: '8200'
        quick: true
        log: false
        state: 'present'

    redstone_rules:
      allow_redstone_to_core_dns:
        action: 'pass'
        int: ['opt2']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP/UDP'
        src: '10.2.100.0/24'
        dest: 'CORE_DNS'
        dest_port: '53'
        quick: true
        log: false
        state: 'present'

      allow_vlan_redstone_out_https:
        action: 'pass'
        int: ['opt2']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP/UDP'
        src: '10.2.100.0/24'
        dest: 'any'
        dest_port: '443'
        quick: true
        log: false
        state: 'present'

    identity_rules:
      allow_identity_to_core_dns:
        action: 'pass'
        int: ['opt3']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP/UDP'
        src: '10.1.110.0/24'
        dest: 'CORE_DNS'
        dest_port: '53'
        quick: true
        log: false
        state: 'present'

      allow_vlan_identity_out:
        action: 'pass'
        int: ['opt3']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP'
        src: '10.1.110.0/24'
        dest: 'any'
        dest_port: 'https'
        quick: true
        log: false
        state: 'present'

    secrets_rules:
      allow_secrets_to_core_dns:
        action: 'pass'
        int: ['opt4']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP/UDP'
        src: '10.1.115.0/24'
        dest: 'CORE_DNS'
        dest_port: '53'
        quick: true
        log: false
        state: 'present'

      allow_vlan_secrets_out:
        action: 'pass'
        int: ['opt4']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP'
        src: 'SECRETS_NET'
        dest: 'any'
        dest_port: 'https'
        quick: true
        log: false
        state: 'present'

      allow_secrets_to_core_lb_vault:
        action: 'pass'
        int: ['opt4']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP'
        src: 'SECRETS_VAULT'
        dest: 'CORE_LBS'
        dest_port: '443'
        quick: true
        log: false
        state: 'present'

      allow_secrets_to_core_loki:
        action: 'pass'
        int: ['opt4']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP'
        src: 'SECRETS_VAULT'
        dest: '10.1.100.19'
        dest_port: '3100'
        quick: true
        log: false
        state: 'present'

      allow_secrets_vault_to_redstone_k8s:
        action: 'pass'
        int: ['opt4']
        dir: 'in'
        ip_proto: 'inet'
        proto: 'TCP'
        src: 'SECRETS_VAULT'
        dest: 'REDSTONE_K8S_MASTER'
        dest_port: '6443'
        quick: true
        log: false
        state: 'present'

    core_aliases:
      - name: 'CORE_BACKUP'
        content: ['10.1.100.14', '10.1.100.15']
      - name: 'CORE_DNS'
        content: ['10.1.100.11', '10.1.100.12']
      - name: 'CORE_LBS'
        content: ['10.1.100.17', '10.1.100.18', '10.1.100.250']

    secrets_aliases:
      - name: 'SECRETS_VAULT'
        content: ['10.1.115.11', '10.1.115.12', '10.1.115.13']
      - name: 'SECRETS_NET'
        content: ['10.1.115.11', '10.1.115.12', '10.1.115.13']

    identity_aliases:
      - name: 'IDENTITY_KEYCLOAK'
        content: ['10.1.115.11']
      - name: 'IDENTITY_NET'
        content: ['10.1.115.11']

    redstone_aliases:
      - name: 'REDSTONE_K8S_MASTER'
        content: ['10.2.100.12']

    aliases: >-
      {{
          core_aliases
        + secrets_aliases
        + identity_aliases
        + redstone_aliases
      }}

    rules: >-
      {{
        mgmt_rules
        | combine(core_rules)
        | combine(redstone_rules)
        | combine(secrets_rules)
        | combine(identity_rules)
      }}

  tasks:
    - name: Setup Aliases
      oxlorg.opnsense.alias:
        name: "{{ item.name }}"
        content: "{{ item.content }}"
      loop: "{{ aliases }}"

    - name: Setup Vlans
      oxlorg.opnsense.interface_vlan:
        description: "{{ item.description }}"
        interface: "{{ item.interface }}"
        vlan: "{{ item.vlan }}"
      loop: "{{ vlans }}"

    - name: Setup Firewall Rules
      oxlorg.opnsense.rule:
        description: "{{ rule_id }}"

        action: "{{ rule.action | default(omit) }}"
        interface: "{{ rule.int | default(omit) }}"
        direction: "{{ rule.dir | default(omit) }}"
        ip_protocol: "{{ rule.ip_proto | default(omit) }}"
        protocol: "{{ rule.proto | default(omit) }}"

        source_invert: "{{ rule.src_invert | default(omit) }}"
        source_net: "{{ rule.src | default(omit) }}"
        source_port: "{{ rule.src_port | default(omit) }}"
        destination_invert: "{{ rule.dest_invert | default(omit) }}"
        destination_net: "{{ rule.dest | default(omit) }}"
        destination_port: "{{ rule.dest_port | default(omit) }}"

        sequence: "{{ rule.seq | default(omit) }}"
        quick: "{{ rule.quick | default(omit) }}"
        log: "{{ rule.log | default(omit) }}"
        gateway: "{{ rule.gw | default(omit) }}"
        state: "{{ rule.state | default(omit) }}"
        enabled: "{{ rule.enabled | default(true) }}"
        # debug: "{{ rule.debug | default(false) }}"

      vars:
        rule: "{{ rule_item.value }}"
        rule_id: "{{ rule_item.key }}"
      loop_control:
        loop_var: rule_item
      with_dict: "{{ rules }}"
