apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/grafana
patches:    
  - target:
      kind: HelmRelease
      name: grafana
    patch: |
      - op: add
        path: /spec/values/admin
        value: 
          existingSecret: vault-grafana
          admin-user: username
          admin-password: password

