name: Ansible Workflow

env:
  ANSIBLE_VAULT: ${{ secrets.ANSIBLE_VAULT }}
  ANSIBLE_SSH_KEY: ${{ secrets.SSH_KEY }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

on:
  workflow_call:
    inputs:
      on:
        type: string
        description: "Get 'all' or only 'changed' dirs"
        default: "changed"
      check_mode:
        type: string
        description: "Run Playbook in Check Mode"
        default: "true"
  workflow_dispatch:
    inputs:
      on:
        type: string
        description: "Get 'all' or only 'changed' dirs"
        default: "all"
      check_mode:
        type: string
        description: "Run Playbook in Check Mode"
        default: "true"

jobs:
  get-dirs:
    uses: ./.github/workflows/get-dirs.yml
    with:
      base_dir: "ansible/inventory"
      on: "${{ inputs.on }}"
      min_depth: "3"
      max_depth: "4"

  ansible-init:
    needs: get-dirs
    uses: ./.github/workflows/ansible-init.yml
    with:
      dirs: "${{ needs.get-dirs.outputs.dirs}}"

  ansible-playbooks-check:
    needs: ansible-init
    if: needs.ansible-init.outputs.can_run == 'true' &&
        github.ref != 'refs/heads/main' &&
        inputs.check_mode == 'true'

    uses: ./.github/workflows/ansible-playbook.yml
    secrets: inherit
    with:
      matrix: "${{ needs.ansible-init.outputs.matrix }}"
      check_mode: "true"

  ansible-playbooks-deploy:
    needs: ansible-init
    if: needs.ansible-init.outputs.can_run == 'true' &&
        github.ref == 'refs/heads/main'
    uses: ./.github/workflows/ansible-playbook.yml
    secrets: inherit
    with:
      matrix: "${{ needs.ansible-init.outputs.matrix }}"
      check_mode: "false"
