name: Ansible Workflow

env:
  ANSIBLE_VAULT: ${{ secrets.ANSIBLE_VAULT }}
  ANSIBLE_SSH_KEY: ${{ secrets.SSH_KEY }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

on:
  workflow_call:
    inputs:
      on:
        type: string
        description: "Get 'all' or only 'changed' dirs"
        default: "changed"
  workflow_dispatch:
    inputs:
      on:
        type: string
        description: "Get 'all' or only 'changed' dirs"
        default: "all"

jobs:
  get-dirs:
    uses: ./.github/workflows/get-dirs.yml
    with:
      base_dir: "ansible/inventory"
      on: "${{ inputs.on }}"
      min_depth: "3"
      max_depth: "4"

  ansible-init:
    needs: get-dirs
    uses: ./.github/workflows/ansible-init.yml
    with:
      dirs: "${{ needs.get-dirs.outputs.dirs}}"

  ansible-playbooks:
    needs: ansible-init
    if: needs.ansible-init.outputs.can_run == 'true' &&
        github.event.pull_request.merged == true
    uses: ./.github/workflows/ansible-playbook.yml
    secrets: inherit
    with:
      matrix: "${{ needs.ansible-init.outputs.matrix }}"
