name: Ansible Init

on:
  workflow_call:
    outputs:
      matrix:
        value: ${{ jobs.init.outputs.playbook_mapping }}
        description: "Playbook and Env mapping"
      can_run:
        value: ${{ jobs.init.outputs.playbooks_found }}
        description: "Playbook and Env mapping"
    inputs:
      dirs:
        required: true
        type: string

jobs:
  init:
    runs-on: self-hosted
    container:
      image:  reneruprecht/ci-python312
    outputs:
      playbook_mapping: ${{ steps.setup.outputs.playbook_mapping }}
      playbooks_found: ${{ steps.check_playbook.outputs.playbooks_found }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Playbooks mapping
        working-directory: "ansible"
        env:
          JSON_DIRS: "${{ inputs.dirs }}"
        id: setup
        run: |
          JSON="${JSON_DIRS}"

          RESULT=$(python3 select_playbook.py "$JSON" | jq -c .)

          {
            echo "playbook_mapping<<EOF"
            echo "$RESULT"
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Check if Playbook exists
        id: check_playbook
        run: |
          MAPPING="${{ steps.setup.outputs.playbook_mapping }}"
          if [ "$MAPPING" = "[]" ]; then
            {
              echo "## ℹ️ **INFO: NO PLAYBOOKS TO RUN!** ℹ️"
              echo '```'
              echo "#########################################"
              echo "###                                   ###"
              echo "###   ℹ️    NO PLAYBOOKS TO RUN   ℹ️  ###"
              echo "###                                   ###"
              echo "#########################################"
              echo '```'
            } >> $GITHUB_STEP_SUMMARY

            {
              echo "playbooks_found<<EOF"
              echo "false"
              echo "EOF"
            } >> $GITHUB_OUTPUT

          else
            {
              echo "playbooks_found<<EOF"
              echo "true"
              echo "EOF"
            } >> $GITHUB_OUTPUT

            {
              echo "## ℹ️ **CHANGES DETECTED** ℹ️"
              echo '```'
              echo "##############################################"
              echo "###                                        ###"
              echo "###  ℹ️   PLAYBOOKS WILL BE EXECUTED   ℹ️  ###"
              echo "###                                        ###"
              echo "##############################################"
              echo ""
              echo '```'
            } >> $GITHUB_STEP_SUMMARY


              JSON='${{ steps.setup.outputs.playbook_mapping }}'

            {
              echo "| Playbook | Env |"
              echo "|----------|-----|"
              echo "$JSON" | jq -r '.[] | "| \(.playbook) | \(.env) |"'
            } >> $GITHUB_STEP_SUMMARY

          fi
