name: Branch Terraform Workflow

on:
  push:
    paths:
      - 'terraform/environments/**/**'
    branches:
      - 'feat/**'
      - 'fix/**'
      - 'refactor/**'
      - 'chore/**'

jobs:
  get-dirs:
    uses: ./.github/workflows/get-dirs.yml
    with:
      base_dir: "terraform/environments"
      processing_mode: "changed"

  terraform-plan:
    uses: ./.github/workflows/terraform-plan.yml
    needs: get-dirs
    secrets: inherit
    with:
      dirs: "${{ needs.get-dirs.outputs.dirs }}"
