name: Deploy Terraform Workflow

on:
  push:
    paths:
      - 'terraform/environments/**/**'
    branches:
      - main

jobs:
  get-dirs:
    uses: ./.github/workflows/get-dirs.yml
    with:
      base_dir: "terraform/environments"

  terraform-apply:
    uses: ./.github/workflows/terraform-apply.yml
    needs: get-dirs
    secrets: inherit
    with:
      dirs: "${{ needs.get-dirs.outputs.dirs }}"
