name: Deploy Terraform Workflow

on:
  push:
    paths:
      - 'terraform/environments/**/**'
    branches:
      - main

jobs:
  resolve:
    uses: ./.github/workflows/resolve-changes.yml
    with:
      mode: "terraform"

  terraform-apply:
    uses: ./.github/workflows/terraform-apply.yml
    needs: resolve
    secrets: inherit
    with:
      matrix_data: "${{ needs.resolve.outputs.matrix_data }}"
