name: Deploy Ansible Workflow

on:
  push:
    paths:
      - 'ansible/inventory/**/**'
      - 'ansible/playbook/**/**'
    branches:
      - main

env:
  ANSIBLE_VAULT: ${{ secrets.ANSIBLE_VAULT }}
  ANSIBLE_SSH_KEY: ${{ secrets.SSH_KEY }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  resolve:
    uses: ./.github/workflows/resolve-changes.yml
    with:
      mode: "ansible"

  filter-dns:
    needs: resolve
    if: needs.resolve.outputs.matrix_data != '' &&
        needs.resolve.outputs.matrix_data != '[]' &&
        github.ref == 'refs/heads/main'
    uses: ./.github/workflows/ansible-filter-playbook.yml
    with:
      filter: "dns"
      playbook_env_mapping: "${{ needs.resolve.outputs.matrix_data }}"

  deploy-dns:
    needs: [resolve, filter-dns]
    if: needs.filter-dns.outputs.playbook_env_mapping != '' &&
        needs.filter-dns.outputs.playbook_env_mapping != '[]' &&
        github.ref == 'refs/heads/main'
    uses: ./.github/workflows/ansible-playbook.yml
    secrets: inherit
    with:
      playbook_env_mapping: "${{ needs.filter-dns.outputs.playbook_env_mapping }}"
      check_mode: "false"

  filter-lb:
    needs: [resolve, deploy-dns]
    if: always() && 
        needs.resolve.outputs.matrix_data != '' &&
        needs.resolve.outputs.matrix_data != '[]' &&
        github.ref == 'refs/heads/main'
    uses: ./.github/workflows/ansible-filter-playbook.yml
    with:
      filter: "loadbalancer"
      playbook_env_mapping: "${{ needs.resolve.outputs.matrix_data }}"

  deploy-lb:
    needs: [resolve, filter-lb]
    if: always() && 
        needs.filter-lb.outputs.playbook_env_mapping != '' &&
        needs.filter-lb.outputs.playbook_env_mapping != '[]' &&
        github.ref == 'refs/heads/main'
    uses: ./.github/workflows/ansible-playbook.yml
    secrets: inherit
    with:
      playbook_env_mapping: "${{ needs.filter-lb.outputs.playbook_env_mapping }}"
      check_mode: "false"

  filter-extra:
    needs: [resolve, deploy-dns, deploy-lb]
    if: always() && 
        needs.resolve.outputs.matrix_data != '' &&
        needs.resolve.outputs.matrix_data != '[]' &&
        github.ref == 'refs/heads/main'
    runs-on: homelab
    container:
      image: reneruprecht/ci-python312
    outputs:
      playbook_env_mapping: ${{ steps.filter_extra.outputs.playbook_env_mapping }}
    steps:
      - name: filter_extra
        id: filter_extra
        run: |
          INPUT_PLAYBOOK_ENV_MAPPING='${{ needs.resolve.outputs.matrix_data }}'

          PLAYBOOK_ENV_MAPPING=$(echo "$INPUT_PLAYBOOK_ENV_MAPPING" | jq -c '[
            .[] | select(
              (.playbook | startswith("dns") | not) and
              (.playbook | startswith("loadbalancer") | not)
            )
          ]')

          echo "$PLAYBOOK_ENV_MAPPING"

          {
            echo "playbook_env_mapping<<EOF"
            echo "$PLAYBOOK_ENV_MAPPING"
            echo "EOF"
          } >> $GITHUB_OUTPUT

  deploy-extra:
    needs: [filter-extra]
    if: always() && 
        needs.filter-extra.outputs.playbook_env_mapping != '' &&
        needs.filter-extra.outputs.playbook_env_mapping != '[]' &&
        github.ref == 'refs/heads/main'
    uses: ./.github/workflows/ansible-playbook.yml
    secrets: inherit
    with:
      playbook_env_mapping: "${{ needs.filter-extra.outputs.playbook_env_mapping }}"
      check_mode: "false"
