name: Pr Ansible Workflow

on:
  pull_request:
    paths:
      - 'ansible/inventory/**/**'
      - 'ansible/playbook/**/**'
    branches:
      - main

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  ANSIBLE_VAULT: ${{ secrets.ANSIBLE_VAULT }}
  ANSIBLE_SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:
  resolve:
    uses: ./.github/workflows/resolve-changes.yml
    with:
      mode: "ansible"

  ansible-playbooks-check:
    needs: resolve
    uses: ./.github/workflows/ansible-playbook.yml
    secrets: inherit
    with:
      playbook_env_mapping: "${{ needs.resolve.outputs.matrix_data }}"
      check_mode: "true"
