name: PR Docker Workflow

on:
  pull_request:
    paths:
      - 'docker/ci/**/**'
    branches:
      - main

jobs:
  get-dirs:
    uses: ./.github/workflows/get-dirs.yml
    with:
      base_dir: "docker"
      processing_mode: "changed"

  docker:
    if: ${{ needs.get-dirs.outputs.matrix_data != '[]' }}
    container:
      image:  "docker:28.3.3-dind-alpine3.22"
    needs: get-dirs
    runs-on: homelab
    strategy:
      matrix:
        include: ${{ fromJSON(needs.get-dirs.outputs.matrix_data) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build
        working-directory: "docker/${{ matrix.path }}"
        id: build
        run: |
          set -euo pipefail

          IMG_NAME="$(echo "${{ matrix.path }}" | tr '/' '-')"
          IMAGE="local/${IMG_NAME}"

          TAG="pr-${GITHUB_SHA::7}"

          echo "Building test image: ${IMAGE}:${TAG}"

          docker build \
            -t "${IMAGE}:${TAG}" \
            .
