name: PR Docker Workflow

on:
  pull_request:
    paths:
      - 'docker/ci/**/**'
    branches:
      - main

jobs:
  resolve:
    uses: ./.github/workflows/resolve-changes.yml
    with:
      mode: "docker"

  docker:
    if: ${{ needs.resolve.outputs.matrix_data != '[]' }}
    container:
      image:  "docker:28.3.3-dind-alpine3.22"
    needs: resolve
    runs-on: homelab
    strategy:
      matrix:
        include: ${{ fromJSON(needs.resolve.outputs.matrix_data) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build
        working-directory: "docker/${{ matrix.path }}"
        id: build
        run: |
          set -euo pipefail

          IMG_NAME="$(echo "${{ matrix.path }}" | tr '/' '-')"
          IMAGE="local/${IMG_NAME}"

          TAG="pr-${GITHUB_SHA::7}"

          echo "Building test image: ${IMAGE}:${TAG}"

          docker build \
            -t "${IMAGE}:${TAG}" \
            .
