name: Pr Terraform Workflow

on:
  pull_request:
    paths:
      - 'terraform/environments/**/**'
    branches:
      - main

jobs:
  resolve:
    uses: ./.github/workflows/resolve-changes.yml
    with:
      mode: "terraform"

  terraform-plan:
    uses: ./.github/workflows/terraform-plan.yml
    needs: resolve
    secrets: inherit
    with:
      matrix_data: "${{ needs.resolve.outputs.matrix_data }}"
