name: Terraform get changed dirs only

on:
  workflow_call:
    inputs:
      base_dir:
        required: true
        type: string
    outputs:
      dirs:
        value: ${{ jobs.terraform-changed-dirs.outputs.dirs }}
        description: "Json of changed directories"

jobs:
  terraform-changed-dirs:
    runs-on: self-hosted
    outputs:
      dirs: ${{ steps.changed_dirs.outputs.dirs }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find all changed terraform dirs
        id: changed_dirs
        run: |
          echo "Detecting changed components..."
          CHANGED_DIRS=$(git diff --name-only HEAD~1 HEAD \
            | grep '^${{ inputs.base_dir }}/' \
            | awk -F/ '{print $3"/"$4}' \
            | sort -u)

          if [ -z "$CHANGED_DIRS" ]; then
            JSON="[]"
          else
            JSON=$(echo "$CHANGED_DIRS" | jq -R . | jq -s .)
          fi

          {
            echo "dirs<<EOF"
            echo "$JSON"
            echo "EOF"
          } >> $GITHUB_OUTPUT

          {
            echo "# Changed terraform dirs"
            echo "$CHANGED_DIRS" | sed 's/^/📁 /' | sed 's/$/<br>/'
          } >> $GITHUB_STEP_SUMMARY
