name: Terraform Workflow


on:
  push:
    paths:
      - 'terraform/environments/**/**'
    branches:
      - main
      - 'feat/**'
      - 'fix/**'
  pull_request:
    paths:
      - 'terraform/environments/**/**'
    branches:
      - main
    types:
      - closed

env:
  TF_VERSION: 1.12.2
  TERRAFORM_STATE_ADDRESS: ${{ secrets.TERRAFORM_STATE_ADDRESS }}
  NETBOX_SERVER_URL: ${{ secrets.NETBOX_URL }}
  NETBOX_API_TOKEN: ${{ secrets.NETBOX_TOKEN }}
  TF_VAR_vm_user: ${{ secrets.VM_USER }}
  TF_VAR_vm_ssh_keys: ${{ secrets.VM_KEYS }}
  PM_API_URL: ${{ secrets.PM_API_URL }}
  PM_API_TOKEN_ID: ${{ secrets.PM_API_TOKEN_ID }}
  PM_API_TOKEN_SECRET: ${{ secrets.PM_API_TOKEN_SECRET }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  get-dirs:
    uses: ./.github/workflows/get-dirs.yml
    with:
      base_dir: "terraform/environments"
      on: "changed"

  terraform-plan:
    uses: ./.github/workflows/terraform-plan.yml
    needs: get-dirs
    secrets: inherit
    with:
      dirs: "${{ needs.get-dirs.outputs.dirs }}"

  terraform-apply:
    uses: ./.github/workflows/terraform-apply.yml
    if: github.event.pull_request.merged == true
    needs: 
      - get-dirs
      - terraform-plan
    secrets: inherit
    with:
      dirs: "${{ needs.get-dirs.outputs.dirs }}"
    
